### ISSUE TITLE
android IllegalStateException

### ISSUE THREAD

**Issue by mrThinBone** [jsierles/react-native-audio#146]
`Exception in native call
                                                                      java.lang.IllegalStateException
                                                                          at android.media.MediaRecorder.native_start(Native Method)
                                                                          at android.media.MediaRecorder.start(MediaRecorder.java:779)
                                                                          at com.rnim.rn.audio.AudioRecorderManager.startRecording(AudioRecorderManager.java:167)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
                                                                          at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
                                                                          at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                          at android.os.Handler.handleCallback(Handler.java:733)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                          at android.os.Looper.loop(Looper.java:136)
                                                                          at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                          at java.lang.Thread.run(Thread.java:841)`

Have anyone encounter this problem? Have no clue to fix it.

**Comment by mrThinBone** [comment]
missed this step

On Android you need to add a permission to AndroidManifest.xml:

<uses-permission android:name="android.permission.RECORD_AUDIO" />

**Comment by Balasnest** [comment]
Getting this issue in android 9. Any idea??

```
<!--- Camera Permissions -->
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>
    <uses-permission android:name="android.permission.RECORD_VIDEO"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
````

**Comment by hsnMoghadasi** [comment]
same here
