### ISSUE TITLE
App crashes on Microphone Permission request (coded based on the example)

### ISSUE THREAD

**Issue by VanessaChu** [jsierles/react-native-audio#270]
### Tell us which versions you are using ( you can see the versions in your package.json ):

react-native-audio :  4.1.3
react-native : 0.46.4
react :  16.0.0-alpha.12
using react-native-sound ? Yes/No

### Expected behaviour :

Supposed to request permission without crashing

### Actual behaviour

App crashes as soon as Microphone request dialogue pops up.

### Steps to reproduce

I used the example from the AudioExample.js, but it crashes on this section of the code.

```
  componentDidMount () {
    console.log('RecordVoice.componentDidMount()')
    this._checkPermission().then((hasPermission) => {
      this.setState({ hasPermission })

      if (!hasPermission) return

      this.prepareRecordingPath(this.state.audioPath)

      AudioRecorder.onProgress = (data) => {
        this.setState({ currentTime: Math.floor(data.currentTime) })
      }

      AudioRecorder.onFinished = (data) => {
        // Android callback comes in the form of a promise instead.
        if (Platform.OS === 'ios') {
          this._finishRecording(data.status === 'OK', data.audioFileURL)
        }
      }
    })
  }
```

### Link to a git repo that reproduces bug 

If you put a GitHub repo that reproduces your issue then you significantly increase your chances of getting help !

**Comment by jsierles** [comment]
Can you post the specific error? Thanks.

**Comment by n1ru4l** [comment]
@jsierles I get the following error on android, it works fine on iOS

```
07-18 17:17:05.930 597-597/? E/MediaRecorderService: Request requires android.permission.RECORD_AUDIO
07-18 17:17:05.930 31638-31690/? E/ReactNativeAudio: Make sure you've added RECORD_AUDIO permission to your AndroidManifest.xml file setAudioSource failed.
07-18 17:17:05.931 31638-31690/? E/MediaRecorder: start called in an invalid state: 0
07-18 17:17:05.939 31638-31690/? D/io.sentry.android.event.helper.AndroidEventBuilderHelper: Proguard UUIDs file not found.
07-18 17:17:05.949 549-723/? I/SFPerfTracer:      triggers: (rate: 0:3) (0 sw vsyncs) (0 skipped) (617:679287 vsyncs) (619:684950)
07-18 17:17:06.068 31638-31690/? W/System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
    SLF4J: Defaulting to no-operation MDCAdapter implementation.
    SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
07-18 17:17:06.073 31638-31690/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: de.groovecat.staging, PID: 31638
    java.lang.IllegalStateException
        at android.media.MediaRecorder.start(Native Method)
        at com.rnim.rn.audio.AudioRecorderManager.startRecording(AudioRecorderManager.java:190)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:154)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:761)
```

I already added `<uses-permission android:name="android.permission.RECORD_AUDIO"/>`  to my `AndroidManifest.xml`

**Comment by vynogradskyi** [comment]
HI @VanessaChu not sure if it helps. 
1) I'm not sure what this._checkPermission do, but it should run AudioRecorder.requestAuthorization().
2) For some reason on Android i had AudioRecorder.requestAuthorization = undefined
3) So you may want to try React Native Permissions or react-native-permissions to request permission first, and then perform all your actions

**Comment by gavin-gmlab** [comment]
Having the same problem. App crashes upon pressing the record button. Upon investigation, it is because of the permissions. I also have the RECORD_AUDIO permission setting in the manifest file. 

If I go to the settings->app->permissions and manually enable microphone, no crash is seen.

This is on a Galaxy s9

**Comment by n1ru4l** [comment]
@gavin-gmlab  Did you call `AudioRecorder.requestAuthorization()` before starting the recording?

**Comment by gavin-gmlab** [comment]
@n1ru4l , I couldn't use that API cause the package is not released to npm with that fix yet. However, I tried using the older _checkPermission code, and the app again crashed. Realized it is because storage permissions were not yet granted. I think the base code should at least not crash if there is a permissions issue but fail gracefully.

**Comment by n1ru4l** [comment]
@jsierles Could you please release a new version?

@gavin-gmlab My fault, I was using the `master` branch instead of the published npm version.

As a workaround you can still check for storage permissions (using [PermissionsAndroid](https://facebook.github.io/react-native/docs/permissionsandroid) until the new version is published to npm OR you could install `master` (`yarn add react-native-audio@git://github.com/jsierles/react-native-audio.git#f3b619daf3048600f076384496176b3407458767` or `npm install react-native-audio@git://github.com/jsierles/react-native-audio.git#f3b619daf3048600f076384496176b3407458767` depending on your preferred package manager).

**Comment by jsierles** [comment]
I have not had time to test the master release yet on both platforms. Meanwhile, you can use the master branch as @n1ru4l suggests here. There is really no difference between the two.

**Comment by elliotfleming** [comment]
For anyone else having issues with permissions consider using [react-native-permissions](https://github.com/yonahforst/react-native-permissions) as mentioned by @vynogradskyi to check microphone permissions instead of the included `AudioRecorder.requestAuthorization()`. They're basically doing the same thing under the hood but `react-native-permissions` is a dedicated package with more support.

**Comment by muchmeat** [comment]
I think we need PermissionsAndroid.WRITE_EXTERNAL_STORAGE  on Android
