### ISSUE TITLE
Cannot Recording on Android 

### ISSUE THREAD

**Issue by Arthuzuga** [jsierles/react-native-audio#318]
## Version

react-native-audio :  ^4.3.0
react-native : 0.58.5
react :  16.6.3
using react-native-sound ? Yes (^0.10.12)

### Expected behaviour : startRecording

What were you trying to do and what did you expect to happen ?
Android:
I'm trying to press my TouchableOpacity to start the recording, and start to Recording
iOS: Works fine
### Actual behaviour
![Captura de Tela 2019-03-15 às 18 08 05](https://user-images.githubusercontent.com/22326922/54463366-94730600-4751-11e9-88b7-df08376b790c.png)

What happened when your issue occurred ? The more details you provide here the better the odds are that someone will help you resolve your issue

i cannot start the recording, and if if dismiss the error i cannot stop

### Steps to reproduce

Create a TouchableOpacity and press to startRecording on Androind

**Comment by aJIEw** [comment]
it's hard to tell what's the root of this error from the screenshot you uploaded, maybe you can provide the native error logs from Android Studio so there might be more useful information.

**Comment by hossamnasser938** [comment]
I'm experiencing the same Error, and here it is from Android Studio.
E/unknown:ReactNative: Exception in native call
    com.facebook.jni.UnknownCppException: Unknown
        at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
        at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:218)
        at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:31)
        at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:247)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1152)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:123)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:943)
        at java.lang.Thread.run(Thread.java:818)

**Comment by chuanhaisoft** [comment]
same error ,rn0.61.5

**Comment by chuanhaisoft** [comment]
it is ok on v4.3.1
