### ISSUE TITLE
crashing on samsung device

### ISSUE THREAD

**Issue by hsnMoghadasi** [jsierles/react-native-audio#367]
react-native-audio :  4.3.0
react-native :0.61.5
react :  16.9.0
using react-native-sound ? Yes

`Fatal Exception: java.lang.RuntimeException: start failed.
       at android.media.MediaRecorder._start(MediaRecorder.java)
       at android.media.MediaRecorder.start(MediaRecorder.java:1175)
       at com.rnim.rn.audio.AudioRecorderManager.startRecording(AudioRecorderManager.java:199)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
       at android.os.Looper.loop(Looper.java:154)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
       at java.lang.Thread.run(Thread.java:762)`

**Devices that have cracked:**
60% Galaxy S8+
13% Galaxy Note5
7% Galaxy A5(2016)
20% Other ( Galaxy S4 ,Galaxy Mega 6.3, Galaxy A50s ,...)

**Comment by sephiroth56** [comment]
Same, did u solve this issue?

**Comment by morneluckybeard** [comment]
Also getting this problem, anyone find a fix yet? @sephiroth56 @hsnMoghadasi ?

**Comment by morneluckybeard** [comment]
So it turns out our problem was relating to a third party app that was already capturing audio. We used look-back as a testing service and the audio capture caused the crash.
