### ISSUE TITLE
Requiring unknown module "react-native-audio".

### ISSUE THREAD

**Issue by cavilaho** [jsierles/react-native-audio#96]
Hello there.

I got an error when running `react-native run-android` which is: `Requiring unknown module "react-native-audio".`
With `react-native log-android` I have the next error too: 

```
Requiring unknown module "react-native-audio".
Module AppRegistry is not a registered callable module (calling runApplication)
```
In fact, if I run `Reload` option on my device, It works fine. 

I have this trouble only with this library. Any ideas?

**Comment by cavilaho** [comment]
PD: If you try to deploy a release APK instead a debug, the error persists and the app closes everytime.

**Comment by jsierles** [comment]
Thanks for posting - I don't have a way to test on Android right now, but will look early next week when I can, unless @RakanNimer can get to it!

**Comment by RakanNimer** [comment]
Will check it out tomorrow ! Thanks for reporting

**Comment by cavilaho** [comment]
Thanks for answer @jsierles @RakanNimer  :)

**Comment by RakanNimer** [comment]
Hey @cavilaho, I just cloned the (repo)[https://github.com/jsierles/react-native-audio] and tried without any problem. Here's what I did : 
```
git clone https://github.com/jsierles/react-native-audio
cd AudioExample
npm install
react-native link react-native-audio
react-native run-android
```

This worked normally on both a device and an emulator. 

Can you give me more details about your setup so I can help further debug ? 
Are you on windows ? Which emulator, device are you using ? 
Maybe you forgot to run npm install from the AudioExample directory ?

Let me know if there's anything I need to know to be able to reproduce and try running the steps I described above to see if they work. 

Have a great day !
Cheers !

**Comment by cavilaho** [comment]
Hello @RakanNimer .

The problem was solved by updating the `adb` on server side (32), due to the client side `adb` was newest (36). After that, running `react-native start` and `react-native run-android` works fine. 

If I only run `react-native run-android` I got this error:
```
Could not get BatchedBridge, make sure your bundle is packaged properly
```

So in debug mode the problem is solved. Now... When I try to get a release variant from my app, the problem persists
```
Requiring unknown module "react-native-audio".
Module AppRegistry is not a registered callable module (calling runApplication)
```
So maybe is a problem with the bundle file or something. I'm pretty lost.

I'm on Android 6.0.1 physical device developing under Ubuntu 16 04. 

Although the problem seems not be from the library, any idea about how to solve this? Have you ever seen this error?

Thanks a lot!

**Comment by RakanNimer** [comment]
Regarding the first problem : 
```
Could not get BatchedBridge, make sure your bundle is packaged properly
```

This usually happens when there is a problem with adb and the react packager can't communicate with your running app. Try : 
``` adb reverse tcp:8081 tcp:8081``` and reload. 

Also try restarting your adb server : 
``` 
adb kill-server 
adb start-server 
```


Regarding the second problem I haven't yet built an app containing this module in release mode, so can't help on that yet. I will try it later and get back to you here to make sure it won't break anything (which it shouldn't)

**Comment by cavilaho** [comment]
Thanks, @RakanNimer . I'll wait for the answer!

:)

**Comment by ahyong87** [comment]
Hi, i also have same problem.

debug mode is work fine, only release mode is crash.

error return by fabric android 

# Crashlytics - plaintext stacktrace downloaded by yong at Wed, 05 Oct 2016 03:43:53 GMT
# URL: https://fabric.io/lizardapps/android/apps/com.reactvoizxl/issues/57f46c8e0aeb16625b25d0c5/sessions/57f46c7403a0000102ea7afc5c032005
# Organization: 
# Platform: android
# Application: 
# Version: 1.0 (1)
# Bundle Identifier: 
# Issue #: 1
# Issue ID: 57f46c8e0aeb16625b25d0c5
# Session ID: 57f46c7403a0000102ea7afc5c032005
# Date: 2016-10-05T02:59:01Z
# OS Version: 5.0
# Device: SM-G900F
# RAM Free: 37.7%
# Disk Free: 44.7%

#0. Crashed: mqt_native_modules: 0 0 0x0000000000000000
       at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:94)
       at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:78)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:139)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:145)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:818)

--

Fatal Exception: com.facebook.react.modules.core.JavascriptException: Requiring unknown module "react-native-audio"., stack:
n@2:700
o@2:404
e@2:326
i@2:188
<unknown>@546:228
o@2:517
e@2:326
i@2:188
<unknown>@12:666
o@2:517
e@2:256
i@2:188
global code@553:9

       at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:94)
       at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:78)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:139)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:145)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:818)

#0. Crashed: mqt_native_modules: 0 0 0x0000000000000000
       at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:94)
       at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:78)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:139)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:145)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:818)

#1. FinalizerWatchdogDaemon
       at java.lang.Object.wait(Object.java)
       at java.lang.Daemons$FinalizerWatchdogDaemon.waitForObject(Daemons.java:239)
       at java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:211)
       at java.lang.Thread.run(Thread.java:818)

#2. AsyncTask #2
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

#3. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:510)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation(DependencyPriorityBlockingQueue.java:197)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.get(DependencyPriorityBlockingQueue.java:236)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:65)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:46)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

#4. mqt_native_modules
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
       at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:400)
       at java.util.concurrent.FutureTask.get(FutureTask.java:162)
       at com.crashlytics.android.core.CrashlyticsExecutorServiceWrapper.executeSyncLoggingException(CrashlyticsExecutorServiceWrapper.java:47)
       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:235)
       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

#5. Queue
       at libcore.io.Posix.android_getaddrinfo(Posix.java)
       at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
       at java.net.InetAddress.lookupHostByName(InetAddress.java:438)
       at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
       at java.net.InetAddress.getAllByName(InetAddress.java:215)
       at com.android.okhttp.HostResolver$1.getAllByName(HostResolver.java:29)
       at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:232)
       at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:124)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:361)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:289)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:323)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:491)
       at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
       at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
       at io.fabric.sdk.android.services.network.HttpRequest.code(HttpRequest.java:1352)
       at io.fabric.sdk.android.services.settings.DefaultSettingsSpiCall.handleResponse(DefaultSettingsSpiCall.java:103)
       at io.fabric.sdk.android.services.settings.DefaultSettingsSpiCall.invoke(DefaultSettingsSpiCall.java:90)
       at io.fabric.sdk.android.services.settings.DefaultSettingsController.loadSettingsData(DefaultSettingsController.java:80)
       at io.fabric.sdk.android.services.settings.DefaultSettingsController.loadSettingsData(DefaultSettingsController.java:64)
       at io.fabric.sdk.android.services.settings.Settings.loadSettingsData(Settings.java:155)
       at io.fabric.sdk.android.Onboarding.retrieveSettingsData(Onboarding.java:123)
       at io.fabric.sdk.android.Onboarding.doInBackground(Onboarding.java:99)
       at io.fabric.sdk.android.Onboarding.doInBackground(Onboarding.java:45)
       at io.fabric.sdk.android.InitializationTask.doInBackground(InitializationTask.java:63)
       at io.fabric.sdk.android.InitializationTask.doInBackground(InitializationTask.java:28)
       at io.fabric.sdk.android.services.concurrency.AsyncTask$2.call(AsyncTask.java:311)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

#6. pool-2-thread-1
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

#7. mqt_js
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:143)
       at android.os.Looper.loop(Looper.java:130)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:818)

#8. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:510)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation(DependencyPriorityBlockingQueue.java:197)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.get(DependencyPriorityBlockingQueue.java:236)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:65)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:46)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

#9. Crashlytics Exception Handler1
       at dalvik.system.VMStack.getThreadStackTrace(VMStack.java)
       at java.lang.Thread.getStackTrace(Thread.java:580)
       at java.lang.Thread.getAllStackTraces(Thread.java:522)
       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.writeSessionEvent(CrashlyticsUncaughtExceptionHandler.java:1024)
       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.writeFatal(CrashlyticsUncaughtExceptionHandler.java:766)
       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.handleUncaughtException(CrashlyticsUncaughtExceptionHandler.java:262)
       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.access$100(CrashlyticsUncaughtExceptionHandler.java:55)
       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler$5.call(CrashlyticsUncaughtExceptionHandler.java:238)
       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler$5.call(CrashlyticsUncaughtExceptionHandler.java:235)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:75)
       at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:30)
       at java.lang.Thread.run(Thread.java:818)

#10. AsyncTask #1
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

#11. FinalizerDaemon
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:422)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:173)
       at java.lang.Thread.run(Thread.java:818)

#12. HeapTrimmerDaemon
       at java.lang.Object.wait(Object.java)
       at java.lang.Daemons$HeapTrimmerDaemon.run(Daemons.java:310)
       at java.lang.Thread.run(Thread.java:818)

#13. GCDaemon
       at java.lang.Object.wait(Object.java)
       at java.lang.Daemons$GCDaemon.run(Daemons.java:341)
       at java.lang.Thread.run(Thread.java:818)

#14. ReferenceQueueDaemon
       at java.lang.Object.wait(Object.java)
       at java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:133)
       at java.lang.Thread.run(Thread.java:818)

#15. Answers Events Handler1
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1048)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:776)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:75)
       at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:30)
       at java.lang.Thread.run(Thread.java:818)

#16. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:510)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation(DependencyPriorityBlockingQueue.java:197)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.get(DependencyPriorityBlockingQueue.java:236)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:65)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:46)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

#17. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:510)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation(DependencyPriorityBlockingQueue.java:197)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.get(DependencyPriorityBlockingQueue.java:236)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:65)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:46)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

#18. main
       at java.lang.ref.Reference.getReferent(Reference.java)
       at java.lang.ref.Reference.get(Reference.java:203)
       at java.util.WeakHashMap.get(WeakHashMap.java:459)
       at com.facebook.react.bridge.JavaScriptModuleRegistry.getJavaScriptModule(JavaScriptModuleRegistry.java:49)
       at com.facebook.react.cxxbridge.CatalystInstanceImpl.getJSModule(CatalystInstanceImpl.java:282)
       at com.facebook.react.cxxbridge.CatalystInstanceImpl.getJSModule(CatalystInstanceImpl.java:277)
       at com.facebook.react.bridge.ReactContext.getJSModule(ReactContext.java:101)
       at com.facebook.react.modules.appstate.AppStateModule.sendAppStateChangeEvent(AppStateModule.java:73)
       at com.facebook.react.modules.appstate.AppStateModule.onHostResume(AppStateModule.java:51)
       at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:161)
       at com.facebook.react.XReactInstanceManagerImpl.moveToResumedLifecycleState(XReactInstanceManagerImpl.java:561)
       at com.facebook.react.XReactInstanceManagerImpl.moveReactContextToCurrentLifecycleState(XReactInstanceManagerImpl.java:925)
       at com.facebook.react.XReactInstanceManagerImpl.setupReactContext(XReactInstanceManagerImpl.java:740)
       at com.facebook.react.XReactInstanceManagerImpl.access$700(XReactInstanceManagerImpl.java:103)
       at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.onPostExecute(XReactInstanceManagerImpl.java:213)
       at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.onPostExecute(XReactInstanceManagerImpl.java:182)
       at android.os.AsyncTask.finish(AsyncTask.java:632)
       at android.os.AsyncTask.access$600(AsyncTask.java:177)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5832)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

#19. OkHttp ConnectionPool
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:197)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2055)
       at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:435)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Comment by ahaus** [comment]
I also have the problem getting the error message when installing and running the release APK on the device.

error message:
```
Requiring unknown module "react-native-audio".
Module AppRegistry is not a registered callable module (calling runApplication)
```

**Comment by ahaus** [comment]
Just tried to build an APK from the AudioExample as provided in this repository. I also get the same error that the module is not found.

React-Native: 0.34.1
Android: 5.0.1
node-js: 6.6.0 npm: 3.10.3

Error logs:
```
10-09 21:52:15.975: E/ReactNativeJS(26036): Requiring unknown module "react-native-audio".
10-09 21:52:15.995: E/AndroidRuntime(26036): FATAL EXCEPTION: mqt_native_modules
10-09 21:52:15.995: E/AndroidRuntime(26036): Process: com.audioexample, PID: 26036
10-09 21:52:15.995: E/AndroidRuntime(26036): com.facebook.react.common.JavascriptException: Requiring unknown module "react-native-audio"., stack:
10-09 21:52:15.995: E/AndroidRuntime(26036): n@2:700
10-09 21:52:15.995: E/AndroidRuntime(26036): o@2:404
10-09 21:52:15.995: E/AndroidRuntime(26036): e@2:326
10-09 21:52:15.995: E/AndroidRuntime(26036): i@2:188
10-09 21:52:15.995: E/AndroidRuntime(26036): <unknown>@375:140
10-09 21:52:15.995: E/AndroidRuntime(26036): o@2:517
10-09 21:52:15.995: E/AndroidRuntime(26036): e@2:326
10-09 21:52:15.995: E/AndroidRuntime(26036): i@2:188
10-09 21:52:15.995: E/AndroidRuntime(26036): <unknown>@12:40
10-09 21:52:15.995: E/AndroidRuntime(26036): o@2:517
10-09 21:52:15.995: E/AndroidRuntime(26036): e@2:256
10-09 21:52:15.995: E/AndroidRuntime(26036): i@2:188
10-09 21:52:15.995: E/AndroidRuntime(26036): global code@377:9
10-09 21:52:15.995: E/AndroidRuntime(26036): 	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:95)
10-09 21:52:15.995: E/AndroidRuntime(26036): 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:79)
10-09 21:52:15.995: E/AndroidRuntime(26036): 	at java.lang.reflect.Method.invoke(Native Method)
10-09 21:52:15.995: E/AndroidRuntime(26036): 	at java.lang.reflect.Method.invoke(Method.java:372)
10-09 21:52:15.995: E/AndroidRuntime(26036): 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:322)
10-09 21:52:15.995: E/AndroidRuntime(26036): 	at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
10-09 21:52:15.995: E/AndroidRuntime(26036): 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
10-09 21:52:15.995: E/AndroidRuntime(26036): 	at android.os.Handler.handleCallback(Handler.java:739)
10-09 21:52:15.995: E/AndroidRuntime(26036): 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-09 21:52:15.995: E/AndroidRuntime(26036): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
10-09 21:52:15.995: E/AndroidRuntime(26036): 	at android.os.Looper.loop(Looper.java:135)
10-09 21:52:15.995: E/AndroidRuntime(26036): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)

```

**Comment by ahaus** [comment]
Looks like I found the problem. 

I had to rename the file `Audio.ios.js` to `index.js`
I also changed the  entry `... "main": "Audio.ios.js" ...` to` .... "main":"index.js" ... `in package.json

I installed the new generated APK to the device and the app starts properly. great.

**Comment by RakanNimer** [comment]
I was able to reproduce. Going to fix it and push update today ! Thanks for raising the issue :D and thanks @ahaus for the suggested solution !

**Comment by RakanNimer** [comment]
Fixed on master, can you give it a try before we publish to npm ? @cavilaho @ahaus @ahyong87

**Comment by cavilaho** [comment]
@RakanNimer It's working perfectly for me at this moment on release mode with master's branch code. Thanks so much!
